//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountCode
    {
        public string AccountCode1 { get; set; }
        public string AccountName { get; set; }
        public string MinimumBal { get; set; }
        public string accno { get; set; }
        public Nullable<decimal> subfees { get; set; }
        public Nullable<decimal> o_bal { get; set; }
        public Nullable<decimal> min_int_ear_bal { get; set; }
        public Nullable<decimal> in_pay_proc { get; set; }
        public Nullable<decimal> s_chgs { get; set; }
        public Nullable<decimal> c_with { get; set; }
        public Nullable<int> acc_clo_no { get; set; }
        public Nullable<decimal> chgs_w_no { get; set; }
        public Nullable<decimal> chgs_wo_no { get; set; }
        public Nullable<decimal> in_house_chq { get; set; }
        public Nullable<decimal> tran_counter_chq { get; set; }
        public Nullable<double> overdraftlimit { get; set; }
        public Nullable<double> withdrawable { get; set; }
    }
}
