//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advance
    {
        public string payrollno { get; set; }
        public string accno { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> advdate { get; set; }
        public Nullable<int> period { get; set; }
        public Nullable<decimal> amntapp { get; set; }
        public Nullable<decimal> amntg { get; set; }
        public Nullable<System.DateTime> expirydate { get; set; }
        public Nullable<bool> locked { get; set; }
        public Nullable<bool> glpost { get; set; }
        public string auditid { get; set; }
        public Nullable<System.DateTime> audittime { get; set; }
        public string serialno { get; set; }
        public string custno { get; set; }
        public string idno { get; set; }
        public Nullable<double> kilo { get; set; }
        public Nullable<double> factor { get; set; }
        public Nullable<decimal> examnt { get; set; }
        public Nullable<decimal> appamnt { get; set; }
        public Nullable<bool> posted { get; set; }
        public string remarks { get; set; }
        public string description { get; set; }
        public string ProductID { get; set; }
        public Nullable<int> IntRate { get; set; }
    }
}
