//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvanceGuarantor
    {
        public long AdvID { get; set; }
        public string AdvNo { get; set; }
        public string AccNo { get; set; }
        public string GuarantorAccNo { get; set; }
        public string GuarantorName { get; set; }
        public decimal Amount { get; set; }
        public bool Cleared { get; set; }
        public System.DateTime Date { get; set; }
    }
}
