//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agentmember
    {
        public int Id { get; set; }
        public string Surname { get; set; }
        public string Other_names { get; set; }
        public string idno { get; set; }
        public string mobile_number { get; set; }
        public string Gender { get; set; }
        public string DOB { get; set; }
        public string fingerprint1 { get; set; }
        public string fingerprint2 { get; set; }
        public string Agentid { get; set; }
    }
}
