//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentMember
    {
        public long ID { get; set; }
        public string IDNo { get; set; }
        public string SurName { get; set; }
        public string OtherNames { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string MobileNo { get; set; }
        public string FingerPrint1 { get; set; }
        public string FingerPrint2 { get; set; }
        public string PosSerialNo { get; set; }
        public Nullable<bool> Registered { get; set; }
        public string AuditID { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
    }
}
