//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class agingsummary
    {
        public long id { get; set; }
        public string loanno { get; set; }
        public string memberno { get; set; }
        public decimal bal { get; set; }
        public long days { get; set; }
        public string Class { get; set; }
        public Nullable<int> Bosa { get; set; }
        public Nullable<decimal> Arrears { get; set; }
    }
}
