//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPRAISAL
    {
        public long LoanID { get; set; }
        public string LoanNo { get; set; }
        public Nullable<System.DateTime> AppraisDate { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<decimal> Allowances { get; set; }
        public string RepayMethod { get; set; }
        public Nullable<decimal> Co_opShares { get; set; }
        public Nullable<decimal> Co_opLoans { get; set; }
        public Nullable<decimal> Shares { get; set; }
        public Nullable<decimal> Loans { get; set; }
        public Nullable<decimal> Deductions { get; set; }
        public Nullable<decimal> AmtRecommended { get; set; }
        public string Reason { get; set; }
        public string AuditID { get; set; }
        public Nullable<System.DateTime> AuditTime { get; set; }
        public string MemberNo { get; set; }
        public decimal Kilos { get; set; }
        public System.DateTime PayslipDate { get; set; }
        public Nullable<double> totalDeductions { get; set; }
        public Nullable<double> tinterest { get; set; }
        public string transactionNo { get; set; }
    }
}
