//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetMovement
    {
        public Nullable<System.DateTime> TransDate { get; set; }
        public string Bcode { get; set; }
        public string DCode { get; set; }
        public string EmCode { get; set; }
        public string AuditId { get; set; }
        public string Remark { get; set; }
        public string assetNo { get; set; }
        public string coopeCode { get; set; }
        public string departCode { get; set; }
        public string mcode { get; set; }
        public Nullable<System.DateTime> tranDate { get; set; }
    }
}
