//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class assetAllocation
    {
        public int allocationId { get; set; }
        public string assetNo { get; set; }
        public string emcode { get; set; }
        public System.DateTime allocationDate { get; set; }
        public int allocTracker { get; set; }
    }
}
