//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class assetcode
    {
        public int assetCode1 { get; set; }
        public string assetname { get; set; }
        public Nullable<double> rate { get; set; }
        public Nullable<int> DepreciationMethodId { get; set; }
        public string mcode { get; set; }
        public System.DateTime auditDate { get; set; }
        public string auditId { get; set; }
        public string Remarks { get; set; }
    }
}
