//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class assetstran
    {
        public int Assettransid { get; set; }
        public Nullable<int> year { get; set; }
        public string Assetsno { get; set; }
        public string Assetname { get; set; }
        public Nullable<double> Dep_val { get; set; }
        public Nullable<decimal> Amountdep_val { get; set; }
        public Nullable<decimal> NRV { get; set; }
        public Nullable<int> quaters { get; set; }
        public Nullable<System.DateTime> transdate { get; set; }
        public Nullable<int> mmonth { get; set; }
        public Nullable<bool> posted { get; set; }
        public string auditid { get; set; }
        public Nullable<System.DateTime> auditdatetime { get; set; }
        public string assetcode { get; set; }
    }
}
