//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class atmLog
    {
        public decimal Id { get; set; }
        public Nullable<System.DateTime> TrDate { get; set; }
        public string Flag { get; set; }
        public string BitMap { get; set; }
        public string iMessage { get; set; }
    }
}
