//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANK
    {
        public string BankCode { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string AuditID { get; set; }
        public System.DateTime AuditTime { get; set; }
        public int islocal { get; set; }
        public string transit { get; set; }
        public string advance { get; set; }
        public string interest { get; set; }
        public string banker { get; set; }
    }
}
