//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankRecon
    {
        public string AccNo { get; set; }
        public Nullable<System.DateTime> ReconDate { get; set; }
        public Nullable<System.DateTime> OpeningBalDate { get; set; }
        public Nullable<decimal> OpeningBal { get; set; }
        public Nullable<decimal> Receipts { get; set; }
        public Nullable<decimal> Payments { get; set; }
        public Nullable<decimal> Unpresented { get; set; }
        public Nullable<decimal> UnCredited { get; set; }
        public Nullable<decimal> DirectCredits { get; set; }
        public Nullable<decimal> DirectDebits { get; set; }
        public Nullable<decimal> StatementBal { get; set; }
        public Nullable<decimal> CashBookBal { get; set; }
        public long ReconId { get; set; }
    }
}
