//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BENSETUP
    {
        public long BenID { get; set; }
        public string BenNo { get; set; }
        public string BenDescription { get; set; }
        public int Taxable { get; set; }
        public string GLAccNo { get; set; }
    }
}
