//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class branch
    {
        public int bid { get; set; }
        public string branchcode { get; set; }
        public string branchname { get; set; }
        public string branchphysicaladdress { get; set; }
        public string branchaddress { get; set; }
        public string branchtelephoneno { get; set; }
        public string email { get; set; }
        public string status { get; set; }
        public Nullable<int> isDefault { get; set; }
        public string CompanyCode { get; set; }
    }
}
