//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class budget
    {
        public long ID { get; set; }
        public string Accno { get; set; }
        public Nullable<long> mmonth { get; set; }
        public Nullable<long> yyear { get; set; }
        public Nullable<decimal> Actual { get; set; }
        public Nullable<decimal> Budgetted { get; set; }
        public Nullable<decimal> Variance { get; set; }
    }
}
