//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Capital_Adequacy_Return
    {
        public int Id { get; set; }
        public string RefNo { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public System.DateTime Processdate { get; set; }
        public int FinancialYear { get; set; }
        public System.DateTime StartYear { get; set; }
        public System.DateTime Endyear { get; set; }
    }
}
