//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashFlowStatement
    {
        public string Activity { get; set; }
        public string GlAcctype { get; set; }
        public int CashFlowId { get; set; }
        public Nullable<double> AMOUNT { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string CompanyName { get; set; }
    }
}
