//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASHPAYMENT
    {
        public long ID { get; set; }
        public string IDNo { get; set; }
        public string Names { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public decimal Amount { get; set; }
        public decimal Commision { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string Description { get; set; }
        public string AuditID { get; set; }
        public System.DateTime AuditTime { get; set; }
    }
}
