//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cash_Shares_Fosa
    {
        public System.DateTime Date { get; set; }
        public string VoucherNo { get; set; }
        public string GrowerNo { get; set; }
        public decimal Amount { get; set; }
    }
}
