//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashTransaction
    {
        public long Cashtransactionid { get; set; }
        public string Customerno { get; set; }
        public string AccNo { get; set; }
        public string AccName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Transdescription { get; set; }
        public Nullable<System.DateTime> Transdate { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public string Chequeno { get; set; }
        public string Transtype { get; set; }
        public string vno { get; set; }
        public Nullable<bool> Posted { get; set; }
        public Nullable<bool> Locked { get; set; }
        public string Auditid { get; set; }
        public Nullable<System.DateTime> AuditTime { get; set; }
        public string userName { get; set; }
    }
}
