//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASHSUMMARY
    {
        public string ZoneID { get; set; }
        public System.DateTime Period { get; set; }
        public decimal GrossAmount { get; set; }
        public decimal Commission { get; set; }
        public decimal NetAmount { get; set; }
        public long ID { get; set; }
    }
}
