//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cashsplit
    {
        public long distribid { get; set; }
        public string identitty { get; set; }
        public string name { get; set; }
        public decimal amount { get; set; }
        public string cheqno { get; set; }
        public string prodid { get; set; }
        public int posted { get; set; }
        public string userid { get; set; }
        public System.DateTime auditdate { get; set; }
    }
}
