//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cheqcomm
    {
        public long chqdepid { get; set; }
        public string cheqno { get; set; }
        public string comm { get; set; }
        public string accno { get; set; }
        public Nullable<System.DateTime> auditdate { get; set; }
        public string userid { get; set; }
    }
}
