//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChequeDeposit
    {
        public long ChequeID { get; set; }
        public string AccNo { get; set; }
        public Nullable<System.DateTime> Datereceived { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> IsLocal { get; set; }
        public string ClearanceDuration { get; set; }
        public string ChequeNo { get; set; }
        public string VNo { get; set; }
        public Nullable<bool> Bounce { get; set; }
        public Nullable<bool> Cleared { get; set; }
        public Nullable<bool> Posted { get; set; }
        public Nullable<bool> Locked { get; set; }
        public string AuditID { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public string BCode { get; set; }
        public string Laccno { get; set; }
        public string gltrans { get; set; }
        public string Bank { get; set; }
        public string Branch { get; set; }
        public Nullable<int> Special { get; set; }
        public Nullable<int> Banked { get; set; }
        public Nullable<System.DateTime> bankeddate { get; set; }
        public string DestinationAccount { get; set; }
        public Nullable<int> status { get; set; }
        public string ctype { get; set; }
        public Nullable<int> maturity { get; set; }
        public string Drawer { get; set; }
    }
}
