//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cheqdepositsetup
    {
        public long cheqid { get; set; }
        public string cheqdepcode { get; set; }
        public string cheqtype { get; set; }
        public string commid { get; set; }
        public Nullable<int> special { get; set; }
        public Nullable<System.DateTime> auditdate { get; set; }
        public string userid { get; set; }
        public Nullable<int> islocal { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<int> affectclearing { get; set; }
        public Nullable<int> affectbounced { get; set; }
    }
}
