//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHEQUE
    {
        public string LoanNo { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string CollectorID { get; set; }
        public string CollectorName { get; set; }
        public Nullable<System.DateTime> DateIssued { get; set; }
        public string ClerkStaffNo { get; set; }
        public string ClerkName { get; set; }
        public string Status { get; set; }
        public string Reasons { get; set; }
        public string AuditID { get; set; }
        public Nullable<System.DateTime> AuditTime { get; set; }
        public string Remarks { get; set; }
        public long ChequeId { get; set; }
        public decimal IntAmount { get; set; }
        public decimal PaidBf { get; set; }
        public Nullable<System.DateTime> IntLoadeddate { get; set; }
        public Nullable<int> Loaded { get; set; }
        public Nullable<double> balance { get; set; }
        public string TransactionNo { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<System.DateTime> Loadeddate { get; set; }
        public Nullable<double> Insuranceload { get; set; }
        public Nullable<double> IntLoad { get; set; }
        public string GroupID { get; set; }
    }
}
