//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cincome
    {
        public long idd { get; set; }
        public string @class { get; set; }
        public string F3 { get; set; }
        public string descr { get; set; }
        public Nullable<decimal> currdate { get; set; }
        public Nullable<decimal> qterdate { get; set; }
        public Nullable<decimal> yydate { get; set; }
        public Nullable<long> period { get; set; }
        public Nullable<long> yyear { get; set; }
        public Nullable<System.DateTime> Startdate { get; set; }
        public Nullable<System.DateTime> Enddate { get; set; }
    }
}
