//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients_Accounts
    {
        public long ID { get; set; }
        public string Phone_No { get; set; }
        public string Sacco_ID { get; set; }
        public string Account_Number { get; set; }
        public Nullable<int> Account_Position { get; set; }
        public Nullable<decimal> Account_Balance { get; set; }
    }
}
