//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLLOANGUAR
    {
        public long id { get; set; }
        public string LoanNo { get; set; }
        public string OwnerId { get; set; }
        public string OwnerName { get; set; }
        public string CollName { get; set; }
        public decimal CostValue { get; set; }
        public decimal CurrentValue { get; set; }
        public decimal AllocatedValue { get; set; }
        public string DocumentNo { get; set; }
        public short Qnty { get; set; }
        public string AuditId { get; set; }
        public System.DateTime AuditDate { get; set; }
    }
}
