//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comprehensive_Income
    {
        public int ID { get; set; }
        public string RefNo { get; set; }
        public string Description { get; set; }
        public decimal CurrentMonth { get; set; }
        public decimal QuarterToDate { get; set; }
        public decimal yearTodate { get; set; }
        public int Financialyear { get; set; }
        public System.DateTime StartYear { get; set; }
        public System.DateTime EndYear { get; set; }
    }
}
