//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contrib1
    {
        public string MemberNo { get; set; }
        public Nullable<System.DateTime> ContrDate { get; set; }
        public Nullable<int> RefNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> ShareBal { get; set; }
        public string TransBy { get; set; }
        public string ChequeNo { get; set; }
        public string ReceiptNo { get; set; }
        public string Locked { get; set; }
        public string Posted { get; set; }
        public string Remarks { get; set; }
        public string AuditID { get; set; }
        public Nullable<System.DateTime> AuditTime { get; set; }
        public long contribid { get; set; }
        public string SharesCode { get; set; }
        public decimal Interest { get; set; }
        public string TransactionNo { get; set; }
        public bool Used { get; set; }
        public decimal TotalInterest { get; set; }
    }
}
