//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cprofile
    {
        public long Compantid { get; set; }
        public string Name { get; set; }
        public string Adress1 { get; set; }
        public string Address2 { get; set; }
        public string Province { get; set; }
        public string FaxNo { get; set; }
        public string PhoneNo { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public string Fiscal { get; set; }
    }
}
