//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRB_Exemption
    {
        public long ID { get; set; }
        public string AccNo { get; set; }
        public string LoanNo { get; set; }
        public System.DateTime Exempt_Date { get; set; }
        public string Exemption_Reason { get; set; }
        public string Exempted_By { get; set; }
        public bool BosaLoan { get; set; }
    }
}
