//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEDUCTION1
    {
        public long DedID { get; set; }
        public string PayrollNo { get; set; }
        public decimal MMonth { get; set; }
        public decimal YYear { get; set; }
        public decimal Amount { get; set; }
        public string DedNo { get; set; }
        public string DedDescription { get; set; }
    }
}
