//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisbursementDeduction
    {
        public System.DateTime TransDate { get; set; }
        public string Accno { get; set; }
        public string LoanNo { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime AuditTime { get; set; }
        public string AuditId { get; set; }
        public string RLOANNO { get; set; }
        public string DESCRIPTION { get; set; }
        public bool Paid { get; set; }
        public string Transactionno { get; set; }
        public long ID { get; set; }
    }
}
