//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EasyMobi_Mobile_Numbers_Update
    {
        public long ID { get; set; }
        public string OldPhoneNo { get; set; }
        public string NewPhoneNo { get; set; }
        public System.DateTime Date { get; set; }
    }
}
