//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPBENEFIT
    {
        public long EmpID { get; set; }
        public string PayrollNo { get; set; }
        public string BenID { get; set; }
        public string BenName { get; set; }
        public decimal Amount { get; set; }
        public int Taxable { get; set; }
    }
}
