//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string PayrollNo { get; set; }
        public string EmpNo { get; set; }
        public string SurName { get; set; }
        public string OtherNames { get; set; }
        public string IDNo { get; set; }
        public string HomeAddress { get; set; }
        public string DOB { get; set; }
        public string Sex { get; set; }
        public string HomeTelNo { get; set; }
        public string Terms { get; set; }
        public Nullable<System.DateTime> EmpDate { get; set; }
        public string DepCode { get; set; }
        public string NSSFCode { get; set; }
        public string NHIFCode { get; set; }
        public string LascCode { get; set; }
        public string MobNo { get; set; }
        public string CompCode { get; set; }
        public string BCode { get; set; }
        public string PinNo { get; set; }
        public string Type { get; set; }
        public string UUser { get; set; }
        public Nullable<System.DateTime> TTime { get; set; }
        public string bank { get; set; }
        public string bankacc { get; set; }
        public byte[] picpath { get; set; }
        public bool status { get; set; }
        public string MemberNo { get; set; }
        public string AccNo { get; set; }
        public System.DateTime RetirementDate { get; set; }
        public string RetirementReason { get; set; }
    }
}
