//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetail
    {
        public string CustomerNo { get; set; }
        public string EmployerCode { get; set; }
        public string PinNo { get; set; }
        public string EmploymentTerms { get; set; }
        public string StationCode { get; set; }
        public string JobRank { get; set; }
        public string PayrollNo { get; set; }
        public string Salary { get; set; }
    }
}
