//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENDMAIN
    {
        public string LoanNo { get; set; }
        public string MinuteNo { get; set; }
        public Nullable<System.DateTime> MeetingDate { get; set; }
        public Nullable<decimal> AmtApproved { get; set; }
        public string Accepted { get; set; }
        public string ChairSigned { get; set; }
        public string SecSigned { get; set; }
        public string MembSigned { get; set; }
        public string Reasons { get; set; }
        public string Remarks { get; set; }
        public string AuditID { get; set; }
        public Nullable<System.DateTime> AuditTime { get; set; }
        public long LoanId { get; set; }
        public string TransactionNo { get; set; }
    }
}
