//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class finpos
    {
        public long id { get; set; }
        public string cluster { get; set; }
        public string @class { get; set; }
        public string decsr { get; set; }
        public string F5 { get; set; }
        public string ddescr { get; set; }
        public Nullable<decimal> amount1 { get; set; }
        public Nullable<decimal> amount2 { get; set; }
        public Nullable<decimal> amount3 { get; set; }
        public Nullable<int> period { get; set; }
        public Nullable<int> yyear { get; set; }
        public Nullable<bool> closed { get; set; }
        public Nullable<System.DateTime> transdate { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> Enddate { get; set; }
        public string Yu { get; set; }
    }
}
