//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public long GrID { get; set; }
        public string GroupID { get; set; }
        public string GroupName { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public string SSCertNo { get; set; }
        public string Address { get; set; }
        public string postalcode { get; set; }
        public string town { get; set; }
        public string TelNo { get; set; }
        public string email { get; set; }
        public string MinuteNo { get; set; }
        public string MeetingDate { get; set; }
        public string meetingpoint { get; set; }
        public string AuditID { get; set; }
        public System.DateTime AuditTime { get; set; }
        public string AccountNo { get; set; }
    }
}
