//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuarantorAmt
    {
        public long GID { get; set; }
        public string GMNo { get; set; }
        public string GAccNo { get; set; }
        public decimal GAmount { get; set; }
        public int Captured { get; set; }
    }
}
