//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INCOME_ZONE
    {
        public string ZoneID { get; set; }
        public string ZoneName { get; set; }
        public string BuyingCentre { get; set; }
        public string ProductID { get; set; }
    }
}
