//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterestTable
    {
        public long id { get; set; }
        public string Loanno { get; set; }
        public string mMemberno { get; set; }
        public string Loancode { get; set; }
        public Nullable<decimal> interest { get; set; }
        public string Recno { get; set; }
        public Nullable<System.DateTime> Loaddate { get; set; }
        public Nullable<bool> Capitalized { get; set; }
    }
}
