//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Investment_Return
    {
        public int Id { get; set; }
        public string RefNo { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Financialyear { get; set; }
        public Nullable<System.DateTime> StartYear { get; set; }
        public Nullable<System.DateTime> Endyear { get; set; }
    }
}
