//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IR
    {
        public long irid { get; set; }
        public Nullable<long> cluster { get; set; }
        public string @class { get; set; }
        public string descr { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<System.DateTime> transdate { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> Enddate { get; set; }
        public Nullable<int> Yyear { get; set; }
    }
}
