//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jointMember
    {
        public long ID { get; set; }
        public string Memberno { get; set; }
        public string IdNo { get; set; }
        public string Names { get; set; }
        public System.DateTime DOB { get; set; }
        public string Sex { get; set; }
        public decimal MobileNo { get; set; }
        public string Photo { get; set; }
        public string Signature { get; set; }
    }
}
