//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTDA_List
    {
        public string GrowerNo { get; set; }
        public string KTDAAccNo { get; set; }
        public string KTDAName { get; set; }
        public string AccNo { get; set; }
        public string Name { get; set; }
    }
}
