//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCharge
    {
        public string LoanCode { get; set; }
        public string AccNo { get; set; }
        public decimal Rate { get; set; }
        public bool Fixed { get; set; }
        public Nullable<decimal> Minimum { get; set; }
        public Nullable<decimal> Maximum { get; set; }
        public Nullable<bool> Range { get; set; }
        public long ID { get; set; }
    }
}
