//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave_Day
    {
        public long ID { get; set; }
        public string LeaveCode { get; set; }
        public string LeaveName { get; set; }
        public int LeaveDays { get; set; }
        public string JobCode { get; set; }
        public string UserID { get; set; }
        public System.DateTime Date { get; set; }
    }
}
