//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loanaging
    {
        public long agid { get; set; }
        public string description { get; set; }
        public Nullable<int> from { get; set; }
        public Nullable<int> upto { get; set; }
        public string percentage { get; set; }
    }
}
