//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan_Standingorder
    {
        public int StoId { get; set; }
        public string AccNo { get; set; }
        public string MemberNo { get; set; }
        public string Loanno { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<bool> mStatus { get; set; }
    }
}
