//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOANGUAR
    {
        public string MemberNo { get; set; }
        public string LoanNo { get; set; }
        public decimal Amount { get; set; }
        public decimal Balance { get; set; }
        public string AuditID { get; set; }
        public System.DateTime AuditTime { get; set; }
        public long LOANID { get; set; }
        public decimal TotalShares { get; set; }
        public decimal AmntGuarOLoans { get; set; }
        public Nullable<int> transfered { get; set; }
        public string Loanee { get; set; }
    }
}
