//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOANBALANCE
    {
        public long ID { get; set; }
        public string LoanNo { get; set; }
        public string PayrollNo { get; set; }
        public string LoanCode { get; set; }
        public double Amount { get; set; }
        public double Balance { get; set; }
        public double Principal { get; set; }
        public double Interest { get; set; }
        public System.DateTime DateIssued { get; set; }
        public System.DateTime LastTransDate { get; set; }
        public short Period { get; set; }
        public string RepayMethod { get; set; }
    }
}
