//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOANTYPE_INTEREST
    {
        public string LoanCode { get; set; }
        public string LoanType { get; set; }
        public Nullable<int> RepayPeriod { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public Nullable<decimal> MaxAmount { get; set; }
        public string Guarantor { get; set; }
        public string AuditID { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<System.DateTime> AuditTime { get; set; }
        public string LoanAccNo { get; set; }
        public string InterestAccNo { get; set; }
        public string ContraAcc { get; set; }
        public int LoantoShareRatio { get; set; }
        public short MDTEI { get; set; }
        public bool Penalty { get; set; }
        public string Section { get; set; }
        public string RepayMethod { get; set; }
        public string PPACC { get; set; }
        public string sharescode { get; set; }
        public Nullable<double> LTSRatio { get; set; }
        public int id { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<double> MaxLoans { get; set; }
        public string interestAcc { get; set; }
        public string LLFACC { get; set; }
        public string ProfAccno { get; set; }
        public string LoanAcc { get; set; }
        public Nullable<bool> Bridging { get; set; }
        public Nullable<double> MinimumPaidForTopup { get; set; }
        public Nullable<double> minimumpaidforbridging { get; set; }
        public string penaltyAcc { get; set; }
        public Nullable<double> GPeriod { get; set; }
    }
}
