//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loans_Classification
    {
        public long ID { get; set; }
        public int DayNo { get; set; }
        public string LoanNo { get; set; }
        public System.DateTime Date { get; set; }
        public decimal LoanAmount { get; set; }
        public decimal InterestRate { get; set; }
        public decimal InterestReloaded { get; set; }
        public decimal PrincipalPaid { get; set; }
        public decimal InterestPaid { get; set; }
        public decimal PrincipalArrears { get; set; }
        public decimal InterestArrears { get; set; }
        public string Classification { get; set; }
        public decimal ExpectedPrincipal { get; set; }
        public decimal ExpectedInterest { get; set; }
        public decimal PrincipalBalance { get; set; }
        public decimal InterestBalance { get; set; }
        public string DeptCode { get; set; }
        public bool isLoan { get; set; }
        public string LoanCode { get; set; }
        public string MemberNo { get; set; }
        public bool Processed { get; set; }
        public decimal StoAmt { get; set; }
    }
}
