//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan1
    {
        public string PayrollNo { get; set; }
        public string LoanNo { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public decimal Principal { get; set; }
        public decimal Interest { get; set; }
        public decimal Amount { get; set; }
        public decimal Balance { get; set; }
        public Nullable<System.DateTime> FirstDate { get; set; }
        public string RepMethod { get; set; }
        public string PayType { get; set; }
        public Nullable<System.DateTime> AppDate { get; set; }
        public string Purpose { get; set; }
        public Nullable<int> OOcc { get; set; }
        public string UUser { get; set; }
        public Nullable<System.DateTime> TTime { get; set; }
        public double InterestPaid { get; set; }
        public double InterestBal { get; set; }
    }
}
