//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN
    {
        public long ID { get; set; }
        public string UserLoginID { get; set; }
        public string ttime { get; set; }
        public string WkStation { get; set; }
        public string LogedOut { get; set; }
        public Nullable<System.DateTime> LogoutTime { get; set; }
    }
}
