//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> Transdate { get; set; }
        public string Source { get; set; }
        public string Productcode { get; set; }
        public string ProdType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Refno { get; set; }
        public string Transcode { get; set; }
        public string Users { get; set; }
        public string TransactionNo { get; set; }
        public string Machine { get; set; }
        public string Transtype { get; set; }
    }
}
