//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBERTRAN
    {
        public long ID { get; set; }
        public string MemberNo { get; set; }
        public string GroupID { get; set; }
        public System.DateTime TransDate { get; set; }
        public decimal Deposits { get; set; }
        public decimal LoanRepayment { get; set; }
        public decimal LoanInterest { get; set; }
        public string VoucherNo { get; set; }
        public string TransType { get; set; }
        public string AuditID { get; set; }
        public System.DateTime AuditTime { get; set; }
    }
}
