//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membership_Detail
    {
        public long ID { get; set; }
        public System.DateTime Date { get; set; }
        public string MemberNo { get; set; }
        public string OldName { get; set; }
        public string NewName { get; set; }
        public string OldIDNo { get; set; }
        public string NewIDNo { get; set; }
        public System.DateTime OldDOB { get; set; }
        public System.DateTime NewDOB { get; set; }
        public string OldMobileNo { get; set; }
        public string NewMobileNo { get; set; }
        public string OldGender { get; set; }
        public string NewGender { get; set; }
        public string UserID { get; set; }
        public bool Posted { get; set; }
        public System.DateTime UserDate { get; set; }
        public string SignatoryChanges { get; set; }
    }
}
