//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBERSTO
    {
        public long StoID { get; set; }
        public string STONo { get; set; }
        public string MemberNo { get; set; }
        public string AccNo { get; set; }
        public decimal Amount { get; set; }
        public decimal Balance { get; set; }
        public decimal TotAmount { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime LastTransDate { get; set; }
        public int Stopped { get; set; }
        public string AuditID { get; set; }
        public System.DateTime AuditTime { get; set; }
        public double Arrears { get; set; }
        public string ProductID { get; set; }
    }
}
