//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mobile_Number_Change_Requests
    {
        public long ID { get; set; }
        public string IDNo { get; set; }
        public string OldPhoneNo { get; set; }
        public string NewPhoneNo { get; set; }
        public string AuditID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string FormSerialNo { get; set; }
        public string RequestReason { get; set; }
        public string MachineID { get; set; }
        public bool Changed { get; set; }
        public System.DateTime AuthorizeDate { get; set; }
        public string AuthorizedBy { get; set; }
    }
}
