//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONTHLYDEDUCTION
    {
        public long ID { get; set; }
        public string AccNo { get; set; }
        public string StoNo { get; set; }
        public System.DateTime Period { get; set; }
        public decimal Principal { get; set; }
        public decimal Interest { get; set; }
        public string ProductID { get; set; }
        public string Source { get; set; }
        public string AuditID { get; set; }
        public System.DateTime AuditTime { get; set; }
    }
}
