//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NETPAY
    {
        public long ID { get; set; }
        public string PayrollNo { get; set; }
        public int mMonth { get; set; }
        public int yYear { get; set; }
        public decimal Amount { get; set; }
        public double Relief { get; set; }
        public double PAYE { get; set; }
        public double ChargablePay { get; set; }
        public Nullable<double> BasicPay { get; set; }
        public Nullable<double> GrossPay { get; set; }
        public double BenNonCAsh { get; set; }
        public double Quarters { get; set; }
        public double DefContrAct { get; set; }
        public double DefContrFixed { get; set; }
        public double OwnerOcup { get; set; }
        public double ChPay { get; set; }
        public double Pye { get; set; }
    }
}
