//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class param
    {
        public long paramid { get; set; }
        public string ARcontrol { get; set; }
        public string APcontrol { get; set; }
        public string Acontrol { get; set; }
        public string R_Earnings { get; set; }
        public string P_dep { get; set; }
        public string A_Dep { get; set; }
        public string GeneralLegerOpt { get; set; }
        public string Glposting { get; set; }
    }
}
