//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayBill_Reconcilliation
    {
        public long ID { get; set; }
        public string PhoneNo { get; set; }
        public string TxID { get; set; }
        public string MpesaAccNo { get; set; }
        public string MpesaName { get; set; }
        public System.DateTime TransDate { get; set; }
        public decimal Amount { get; set; }
        public bool Posted { get; set; }
        public System.DateTime PostingDate { get; set; }
        public string AccNo { get; set; }
        public string Name { get; set; }
    }
}
