//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentBooking
    {
        public long ID { get; set; }
        public string VoucherNo { get; set; }
        public string Memberno { get; set; }
        public string Ccode { get; set; }
        public string Name { get; set; }
        public string PayeeDesc { get; set; }
        public string Particulars { get; set; }
        public Nullable<System.DateTime> Transdate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Chequeno { get; set; }
        public string Ptype { get; set; }
        public string auditid { get; set; }
        public System.DateTime audittime { get; set; }
        public Nullable<System.DateTime> datedeposited { get; set; }
        public bool posted { get; set; }
        public string Transactionno { get; set; }
        public string DRAccNo { get; set; }
        public string CRAccNo { get; set; }
    }
}
