//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollMonthSummary
    {
        public string PayrollNo { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Total { get; set; }
        public decimal Acting_allowance { get; set; }
        public decimal Annual_increament { get; set; }
        public decimal Basic_pay { get; set; }
        public decimal Casual_wages { get; set; }
        public decimal House_allowance { get; set; }
        public decimal Leave_pay_and_travel { get; set; }
        public decimal Medical_allowance { get; set; }
        public decimal Overtime { get; set; }
        public decimal Reponsibility_allowance { get; set; }
        public decimal Advance { get; set; }
        public decimal Interest_on_advance { get; set; }
        public decimal Interest_on_loan { get; set; }
        public decimal Loan_rep { get; set; }
        public decimal Nhif { get; set; }
        public decimal Nssf { get; set; }
        public decimal P_a_y_e_ { get; set; }
        public decimal Sacco_shares { get; set; }
        public decimal Staff_welfare { get; set; }
        public decimal Telephone_charges { get; set; }
        public int mmonth { get; set; }
        public string yyear { get; set; }
    }
}
