//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYSUMMARY
    {
        public long PayNo { get; set; }
        public string PayrollNo { get; set; }
        public int mMonth { get; set; }
        public int yYear { get; set; }
        public string TransID { get; set; }
        public decimal Amount { get; set; }
        public string TransDescription { get; set; }
        public string ProdID { get; set; }
    }
}
