//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIN_Lock_Request
    {
        public long ID { get; set; }
        public string IDNo { get; set; }
        public string PhoneNo { get; set; }
        public string AuditID { get; set; }
        public System.DateTime LockDate { get; set; }
        public string FormSerialNo { get; set; }
        public string LockingReason { get; set; }
        public string MachineID { get; set; }
        public bool Locked { get; set; }
        public bool UnlockRequested { get; set; }
        public System.DateTime UnlockRequestDate { get; set; }
        public string UnlockRequestedBy { get; set; }
        public System.DateTime UnlockDate { get; set; }
        public string UnlockedBy { get; set; }
    }
}
