//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosLogin
    {
        public long ID { get; set; }
        public string IDNo { get; set; }
        public string AgencyCode { get; set; }
        public string PosSerialNo { get; set; }
        public System.DateTime LoginTime { get; set; }
    }
}
