//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosReconcilliation
    {
        public long ID { get; set; }
        public System.DateTime InitiationDate { get; set; }
        public string AccNo { get; set; }
        public string VoucherNo { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime CompletionDate { get; set; }
        public string AgencyCode { get; set; }
        public string PosSerialNo { get; set; }
        public string InitiatedBy { get; set; }
        public string Activity { get; set; }
        public bool Posted { get; set; }
        public string ProductID { get; set; }
        public string RefNo { get; set; }
        public string Name { get; set; }
    }
}
