//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosUser
    {
        public int Id { get; set; }
        public string Full_Names { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string MachineId { get; set; }
        public string status { get; set; }
        public Nullable<int> Assigngl { get; set; }
        public Nullable<int> loginbal { get; set; }
        public Nullable<System.DateTime> Date_created { get; set; }
        public string createdby { get; set; }
        public string Fingerprint { get; set; }
    }
}
