//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTSETUP
    {
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public string GLAccNo { get; set; }
        public string ContraGLAccNo { get; set; }
        public string ProcessingFee { get; set; }
        public decimal Amount { get; set; }
        public decimal Percentage { get; set; }
        public int BackOffice { get; set; }
        public int intervals { get; set; }
        public string AuditID { get; set; }
        public System.DateTime AuditTime { get; set; }
    }
}
