//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptBooking
    {
        public long ID { get; set; }
        public string ReceiptNo { get; set; }
        public string Memberno { get; set; }
        public string Ccode { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Transdate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Chequeno { get; set; }
        public string Ptype { get; set; }
        public string auditid { get; set; }
        public System.DateTime auditdatetime { get; set; }
        public Nullable<System.DateTime> datedeposited { get; set; }
        public Nullable<bool> posted { get; set; }
        public string Draccno { get; set; }
        public string Craccno { get; set; }
        public string Ref { get; set; }
        public string RefNo { get; set; }
        public string companycode { get; set; }
        public string Transactionno { get; set; }
        public string Particulars { get; set; }
    }
}
