//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refund
    {
        public string MemberNo { get; set; }
        public string RefundItem { get; set; }
        public System.DateTime BookingDate { get; set; }
        public decimal RefundAmount { get; set; }
        public string AuditId { get; set; }
        public System.DateTime Audittime { get; set; }
        public string RefCode { get; set; }
        public bool Done { get; set; }
    }
}
