//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class repay1
    {
        public string LoanNo { get; set; }
        public string MemberNo { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public Nullable<int> PaymentNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Principal { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public Nullable<decimal> IntrCharged { get; set; }
        public Nullable<decimal> IntrOwed { get; set; }
        public Nullable<decimal> LoanBalance { get; set; }
        public string ReceiptNo { get; set; }
        public string Locked { get; set; }
        public string Posted { get; set; }
        public string Accrued { get; set; }
        public string Remarks { get; set; }
        public string AuditID { get; set; }
        public System.DateTime AuditTime { get; set; }
        public string Transby { get; set; }
        public long RepayId { get; set; }
        public Nullable<decimal> IntrBalance { get; set; }
        public string TransactionNo { get; set; }
    }
}
