//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Risk_Classification
    {
        public int id { get; set; }
        public int Number { get; set; }
        public string Classification { get; set; }
        public int NoOfAccounts { get; set; }
        public decimal OutStanding { get; set; }
        public decimal RequiredProvision { get; set; }
        public decimal Amount { get; set; }
        public int NotLessthan { get; set; }
        public int NotMorethan { get; set; }
        public int Financialyear { get; set; }
        public System.DateTime Startyear { get; set; }
        public System.DateTime Endyear { get; set; }
    }
}
