//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryTran
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> DatePosted { get; set; }
        public string AccountNo { get; set; }
        public string CustomerNo { get; set; }
        public string PayrollNo { get; set; }
        public string AmountPosted { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string PreparedBy { get; set; }
        public Nullable<bool> Posted { get; set; }
        public Nullable<bool> Locked { get; set; }
        public Nullable<long> PERIOD { get; set; }
    }
}
