//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public long id { get; set; }
        public string AccountNo { get; set; }
        public string AccountName { get; set; }
        public string CustomerNo { get; set; }
        public string FOSANo { get; set; }
        public string PayrollNo { get; set; }
        public Nullable<decimal> AmountPosted { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string PreparedBy { get; set; }
        public Nullable<bool> posted { get; set; }
        public Nullable<bool> locked { get; set; }
        public Nullable<System.DateTime> dateposted { get; set; }
        public string PERIOD { get; set; }
        public Nullable<long> batchno { get; set; }
        public Nullable<decimal> batchtotal { get; set; }
        public string VoucherNo { get; set; }
    }
}
