//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavingsAccountsParameter
    {
        public long AccountTypePKID { get; set; }
        public string SingleWithdrawalLimit { get; set; }
        public string WithdrawalInterval { get; set; }
        public string FOSATarriffGuide { get; set; }
        public string MinimumBalance { get; set; }
        public string interestMinBal { get; set; }
        public string ChargeAccBelowMinBal { get; set; }
        public string NoticeForClosingAccount { get; set; }
        public string CommisionForClosingAccount { get; set; }
        public string ClearingCommissionLocalChequeDeposits { get; set; }
        public string ClearingCommissionUpcountryChequeDeposits { get; set; }
        public string SpecialClearanceChargesLocal { get; set; }
        public string SpecialClearanceChargesUpcountry { get; set; }
        public string PeriodDeclareDormancy { get; set; }
        public string FeeForNewPassBook { get; set; }
        public string FeeForReplacingPassbook { get; set; }
        public string WaitingPeriodReplacePassbook { get; set; }
        public string TaxRatePercentage { get; set; }
        public string interestcharged { get; set; }
        public string CashWithcharges { get; set; }
        public Nullable<long> OpeningFee { get; set; }
        public Nullable<decimal> Servicecharge { get; set; }
        public Nullable<decimal> bounce { get; set; }
        public Nullable<decimal> Bankerscheque { get; set; }
        public Nullable<decimal> Group3 { get; set; }
        public Nullable<decimal> Individual3 { get; set; }
        public Nullable<decimal> over30 { get; set; }
        public Nullable<decimal> overamnt { get; set; }
        public Nullable<decimal> mobcharge { get; set; }
        public Nullable<decimal> staff { get; set; }
        public Nullable<int> intonauthorisedod { get; set; }
        public Nullable<int> intonunauthorisedod { get; set; }
        public Nullable<int> intonclearedchqs { get; set; }
        public Nullable<int> intonloans { get; set; }
        public Nullable<decimal> countercharges { get; set; }
        public string staffcode { get; set; }
        public Nullable<decimal> ChqAmntOver { get; set; }
        public Nullable<decimal> PerCharge { get; set; }
        public Nullable<bool> userange { get; set; }
    }
}
