//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionUSSD_BKP
    {
        public long ID { get; set; }
        public string Mobile { get; set; }
        public string SessionID { get; set; }
        public string ServiceCode { get; set; }
        public string Type { get; set; }
        public string Message { get; set; }
        public string Operator { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<System.DateTime> AuditTime { get; set; }
    }
}
