//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHARE
    {
        public string MemberNo { get; set; }
        public Nullable<decimal> TotalShares { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<System.DateTime> LastDivDate { get; set; }
        public string AuditID { get; set; }
        public Nullable<System.DateTime> AuditTime { get; set; }
        public decimal loanbal { get; set; }
        public long SharesID { get; set; }
        public decimal ShareCap { get; set; }
        public string SharesCode { get; set; }
        public decimal initshares { get; set; }
        public double StatementShares { get; set; }
    }
}
