//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sharetype
    {
        public string SharesCode { get; set; }
        public string SharesType { get; set; }
        public string SharesAcc { get; set; }
        public Nullable<int> PlacePeriod { get; set; }
        public Nullable<float> LoanToShareRatio { get; set; }
        public Nullable<int> Issharecapital { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public Nullable<decimal> MaxAmount { get; set; }
        public string Guarantor { get; set; }
        public string AuditID { get; set; }
        public Nullable<System.DateTime> AuditTime { get; set; }
        public string accno { get; set; }
        public string shareboost { get; set; }
        public bool IsMainShares { get; set; }
        public bool UsedToGuarantee { get; set; }
        public string ContraAcc { get; set; }
        public bool UsedToOffset { get; set; }
        public bool Withdrawable { get; set; }
        public bool loanquaranto { get; set; }
        public int Priority { get; set; }
        public decimal MinAmount { get; set; }
        public string PPAcc { get; set; }
        public decimal LowerLimit { get; set; }
        public decimal ElseRatio { get; set; }
        public string InterestAcc { get; set; }
        public Nullable<double> intRate { get; set; }
        public bool @fixed { get; set; }
        public double sharevalue { get; set; }
        public double fseed { get; set; }
    }
}
