//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSSetting
    {
        public int ID { get; set; }
        public bool ActivatesmsAlert { get; set; }
        public bool ChargeSms { get; set; }
        public decimal ChargeAmount { get; set; }
        public string SMSAccNo { get; set; }
        public string SMSComAccNo { get; set; }
        public bool SendAlertOnLoanDisbursment { get; set; }
        public Nullable<bool> SendSmsOnBouncedCheque { get; set; }
        public string FileLocation { get; set; }
        public Nullable<bool> alertloanGuarantors { get; set; }
    }
}
