//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMTDR
    {
        public long id { get; set; }
        public string Class { get; set; }
        public string range { get; set; }
        public string type { get; set; }
        public Nullable<long> noas { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> Yyear { get; set; }
        public Nullable<System.DateTime> Startdate { get; set; }
        public Nullable<System.DateTime> Enddate { get; set; }
        public string LastSent { get; set; }
    }
}
