//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_Leave
    {
        public long ID { get; set; }
        public string PayrollNo { get; set; }
        public string LeaveCode { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Remarks { get; set; }
        public string UserID { get; set; }
        public System.DateTime Date { get; set; }
        public bool Revoked { get; set; }
        public string RevokeReason { get; set; }
        public bool Approved { get; set; }
        public int Days { get; set; }
    }
}
