//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class summarycollection
    {
        public long did { get; set; }
        public string groupno { get; set; }
        public Nullable<System.DateTime> transdate { get; set; }
        public string voucherno { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string transdescription { get; set; }
        public bool posted { get; set; }
        public string userid { get; set; }
        public Nullable<System.DateTime> auditdate { get; set; }
    }
}
