//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysincome
    {
        public long ID { get; set; }
        public string MemberNo { get; set; }
        public string SourceAccNo { get; set; }
        public string Name { get; set; }
        public decimal Amount { get; set; }
        public string ProductID { get; set; }
        public System.DateTime TransDate { get; set; }
        public System.DateTime Period { get; set; }
        public System.DateTime AuditTime { get; set; }
        public string TransDescription { get; set; }
        public string ChequeNo { get; set; }
        public string AccNo { get; set; }
        public int Absent { get; set; }
    }
}
