//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSPARAM
    {
        public Nullable<decimal> LoanInterest { get; set; }
        public Nullable<decimal> ShareInterest { get; set; }
        public Nullable<int> MinGuarantors { get; set; }
        public Nullable<int> MaxGuarantors { get; set; }
        public Nullable<decimal> LoanToShareRatio { get; set; }
        public Nullable<int> MinLoanPeriod { get; set; }
        public Nullable<decimal> MinTotShares { get; set; }
        public Nullable<int> MaxLoans { get; set; }
        public Nullable<int> MaxContribPeriod { get; set; }
        public Nullable<decimal> BankInterest { get; set; }
        public Nullable<int> MinDivPeriod { get; set; }
        public string DefFundID { get; set; }
        public Nullable<decimal> DeductAmt { get; set; }
        public string SelfGuar { get; set; }
        public Nullable<decimal> GuarShareRatio { get; set; }
        public string CompanyName { get; set; }
        public string AuditID { get; set; }
        public Nullable<System.DateTime> AuditTime { get; set; }
        public Nullable<int> ShareMaturity { get; set; }
        public Nullable<int> withdrawalnotice { get; set; }
        public decimal TeaRate { get; set; }
        public decimal ShareCap { get; set; }
        public Nullable<bool> DonotchargeExciseduty { get; set; }
        public Nullable<bool> chkChargeExciseDutyForStaffs { get; set; }
        public Nullable<bool> chkChargeWithdrawalFeeForStaffs { get; set; }
        public string compcode { get; set; }
        public Nullable<double> maturity { get; set; }
        public Nullable<double> TellerAmt { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public string CompanyNo { get; set; }
        public string DefaultedInterestAction { get; set; }
        public string TagLine { get; set; }
        public string Telephone { get; set; }
        public string Town { get; set; }
        public string Address { get; set; }
        public string REarningsAcc { get; set; }
        public string suspenseAcc { get; set; }
        public string CreditorsAcc { get; set; }
    }
}
