//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_CommunicationPorts
    {
        public decimal PortNumber { get; set; }
        public string PortDescription { get; set; }
        public string MessageType { get; set; }
        public string MessageFormat { get; set; }
        public string ListenMode { get; set; }
        public string AllowedIP { get; set; }
        public string RemoteIP { get; set; }
        public string InMessageFormat { get; set; }
        public string OutMessageFormat { get; set; }
        public string ValidCardStart { get; set; }
        public string ValidCardEnd { get; set; }
        public string HostDatabaseServer { get; set; }
        public string HostDatabaseName { get; set; }
        public string HostDatabaseType { get; set; }
        public string HostDatabaseUserID { get; set; }
        public string HostDatabasePassword { get; set; }
        public string MessageArriveProcedure { get; set; }
        public string BeforeSendingProcedure { get; set; }
        public string OnConnectProcedure { get; set; }
        public string OnDisConnectProcedure { get; set; }
        public string MessageHeaderProcedure { get; set; }
        public Nullable<decimal> TimeoutSeconds { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> PortOffline { get; set; }
        public Nullable<decimal> GlobalFloorLimit { get; set; }
        public string ZPK { get; set; }
        public string TPK { get; set; }
    }
}
