//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Devices
    {
        public short DeviceFieldID { get; set; }
        public string DeviceType { get; set; }
        public string DeviceID { get; set; }
        public string ReportingToBranch { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string BranchShortName { get; set; }
        public string POSAccountID { get; set; }
    }
}
