//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_ISOFieldNames
    {
        public decimal FieldID { get; set; }
        public string FieldDescription { get; set; }
        public string FieldFormat { get; set; }
    }
}
