//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_MessageTypes
    {
        public string InMessageType { get; set; }
        public string OutMessageType { get; set; }
        public string ReversalMessageType { get; set; }
        public string SwitchStoredProcedure { get; set; }
        public string HostStoredProcedure { get; set; }
        public string SwitchTimeoutProcedure { get; set; }
        public string HostTimeOutProcedure { get; set; }
        public string ReversalStoredProcedure { get; set; }
        public string WebServiceCall { get; set; }
        public string ReturnMessageProcedure { get; set; }
        public string OfflineStoredProcedure { get; set; }
    }
}
