//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_x
    {
        public string ISOFormatID { get; set; }
        public decimal ISOFieldID { get; set; }
        public string ISOFieldText { get; set; }
        public string ISOFieldFormat { get; set; }
        public string ExcessTrimFrom { get; set; }
        public string ShortPadding { get; set; }
        public string PadChar { get; set; }
    }
}
