//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB
    {
        public long id { get; set; }
        public string tellname { get; set; }
        public string accno { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> tteller { get; set; }
        public Nullable<decimal> tdep { get; set; }
        public Nullable<decimal> twith { get; set; }
        public Nullable<decimal> tmobcomm { get; set; }
        public Nullable<decimal> tbankcom { get; set; }
        public Nullable<decimal> tintadv { get; set; }
        public Nullable<decimal> tnewaccno { get; set; }
        public Nullable<decimal> tadvance { get; set; }
        public Nullable<decimal> tsal { get; set; }
        public Nullable<decimal> tstad { get; set; }
        public Nullable<decimal> ttrea { get; set; }
        public Nullable<decimal> kipsacco { get; set; }
        public Nullable<decimal> tbank { get; set; }
        public Nullable<bool> TRANSTYPE { get; set; }
    }
}
