//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ISOResults
    {
        public decimal ID { get; set; }
        public string CardNumber { get; set; }
        public string ProcessingCode { get; set; }
        public Nullable<decimal> TrxAmount { get; set; }
        public string ResponseCode { get; set; }
        public string inmti { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
    }
}
