//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempStatement
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> transdate { get; set; }
        public string TransDescription { get; set; }
        public Nullable<decimal> DR_Amount { get; set; }
        public Nullable<decimal> CR_Amount { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string vno { get; set; }
        public string transactionNo { get; set; }
        public string Accno { get; set; }
        public Nullable<int> hasloan { get; set; }
    }
}
