//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempGuar
    {
        public System.DateTime Date { get; set; }
        public string SerialNo { get; set; }
        public string MemberNo { get; set; }
        public string GMemberNo { get; set; }
        public string GIDNo { get; set; }
        public string GAccNo { get; set; }
        public string GName { get; set; }
        public string GTelNo { get; set; }
    }
}
