//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST
    {
        public decimal ColNo { get; set; }
        public Nullable<System.DateTime> Trdate { get; set; }
        public string Acc_No { get; set; }
        public Nullable<decimal> TrAmt { get; set; }
        public string TrTrace { get; set; }
    }
}
