//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMPDEDUCTION
    {
        public long ID { get; set; }
        public System.DateTime TransDate { get; set; }
        public string MemberNo { get; set; }
        public string VoucherNo { get; set; }
        public decimal Principal { get; set; }
        public decimal Interest { get; set; }
        public string TransDescription { get; set; }
    }
}
