//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTION
    {
        public long TransID { get; set; }
        public string AccNo { get; set; }
        public decimal Amount { get; set; }
        public string GroupID { get; set; }
        public string TransDescription { get; set; }
        public System.DateTime TransDate { get; set; }
        public string VoucherNo { get; set; }
        public string TransType { get; set; }
        public string ContraAcc { get; set; }
        public int Posted { get; set; }
        public string AuditID { get; set; }
        public System.DateTime AuditTime { get; set; }
        public string transactionno { get; set; }
        public string Machine { get; set; }
    }
}
