//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransCode
    {
        public string Transactioncode { get; set; }
        public string Description { get; set; }
        public string GL { get; set; }
        public string NBal { get; set; }
        public string CommID { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<short> IsPrintable { get; set; }
        public Nullable<bool> BackOffice { get; set; }
        public Nullable<int> PrintBalances { get; set; }
    }
}
