//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIT
    {
        public string UnitCode { get; set; }
        public string UnitName { get; set; }
        public string physicaladdress { get; set; }
        public string ContactTelephone { get; set; }
        public string email { get; set; }
        public string status { get; set; }
        public string jobno { get; set; }
        public long id { get; set; }
    }
}
