//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public string UserName { get; set; }
        public string UserLoginID { get; set; }
        public string mPassword { get; set; }
        public string GroupID { get; set; }
        public string PassExpire { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<long> SUPERUSER { get; set; }
        public string AssignGl { get; set; }
        public string branchcode { get; set; }
        public string levels { get; set; }
        public Nullable<bool> Authorize { get; set; }
        public string Status { get; set; }
        public string Branch { get; set; }
        public Nullable<bool> signed { get; set; }
        public Nullable<short> LoginBal { get; set; }
        public Nullable<System.DateTime> Lastdate { get; set; }
        public string IDNO { get; set; }
        public string WkStation { get; set; }
        public bool POSAdmin { get; set; }
    }
}
