//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vbMicrofinanceCollection
    {
        public Nullable<int> PERIODS { get; set; }
        public string groupid { get; set; }
        public string MemberNo { get; set; }
        public string names { get; set; }
        public string LoanNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> RepayPeriod { get; set; }
        public Nullable<System.DateTime> FirstDate { get; set; }
        public Nullable<decimal> RepayRate { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public decimal arrears { get; set; }
        public Nullable<decimal> principal { get; set; }
        public int shares { get; set; }
    }
}
