//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwBOSALoanee
    {
        public long ID { get; set; }
        public string MemberNo { get; set; }
        public string StaffNo { get; set; }
        public string IDNo { get; set; }
        public string AccNo { get; set; }
        public string Surname { get; set; }
        public string OtherNames { get; set; }
        public string Sex { get; set; }
        public System.DateTime DOB { get; set; }
        public string Employer { get; set; }
        public string Dept { get; set; }
        public string Rank { get; set; }
        public string Terms { get; set; }
        public string PresentAddr { get; set; }
        public string OfficeTelNo { get; set; }
        public string HomeAddr { get; set; }
        public string HomeTelNo { get; set; }
        public Nullable<decimal> RegFee { get; set; }
        public Nullable<decimal> InitShares { get; set; }
        public Nullable<System.DateTime> AsAtDate { get; set; }
        public Nullable<decimal> MonthlyContr { get; set; }
        public Nullable<System.DateTime> ApplicDate { get; set; }
        public Nullable<System.DateTime> EffectDate { get; set; }
        public string Signed { get; set; }
        public string Accepted { get; set; }
        public string Archived { get; set; }
        public string Withdrawn { get; set; }
        public string IsGuarantor { get; set; }
        public string Province { get; set; }
        public string District { get; set; }
        public string Station { get; set; }
        public string CompanyCode { get; set; }
        public string PIN { get; set; }
        public byte[] Photoh { get; set; }
        public Nullable<decimal> ShareCap { get; set; }
        public string BankCode { get; set; }
        public string AuditID { get; set; }
        public Nullable<System.DateTime> AuditTime { get; set; }
        public System.DateTime E_DATE { get; set; }
        public decimal hshares { get; set; }
        public decimal fshares { get; set; }
        public int Dormant { get; set; }
        public string MType { get; set; }
        public string Compcode { get; set; }
        public string Unit { get; set; }
        public string groupid { get; set; }
        public string MobileNo { get; set; }
        public string email { get; set; }
        public string Signature { get; set; }
        public string Location { get; set; }
        public string TelNo { get; set; }
        public string branchcode { get; set; }
        public string MaritalStatus { get; set; }
        public string Division { get; set; }
        public Nullable<int> Active { get; set; }
        public string entrance { get; set; }
        public string companycode1 { get; set; }
        public string Address { get; set; }
        public string category { get; set; }
        public string Photo { get; set; }
        public string LoanNo { get; set; }
        public string LoanCode { get; set; }
        public string Expr1 { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<System.DateTime> FirstDate { get; set; }
        public Nullable<decimal> RepayRate { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public string RepayMethod { get; set; }
        public string Cleared { get; set; }
        public string AutoCalc { get; set; }
        public Nullable<decimal> IntrAmount { get; set; }
        public Nullable<int> RepayPeriod { get; set; }
        public string Remarks { get; set; }
        public string Expr2 { get; set; }
        public Nullable<System.DateTime> Expr3 { get; set; }
        public Nullable<decimal> Loanbal { get; set; }
        public string Expr4 { get; set; }
        public long lid { get; set; }
        public Nullable<decimal> IntBalance { get; set; }
        public Nullable<decimal> Tamount { get; set; }
        public Nullable<System.DateTime> nextduedate { get; set; }
        public Nullable<decimal> Mintbal { get; set; }
        public Nullable<System.DateTime> duedate { get; set; }
        public Nullable<decimal> IntrOwed { get; set; }
        public Nullable<decimal> Penalty { get; set; }
        public Nullable<short> RepayMode { get; set; }
        public Nullable<System.DateTime> IntDate { get; set; }
        public string FQ { get; set; }
        public string TransactionNo { get; set; }
        public Nullable<double> LLF { get; set; }
        public Nullable<double> Loaded { get; set; }
        public Nullable<int> Insurance { get; set; }
        public string Expr5 { get; set; }
        public string Expr6 { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string CollectorID { get; set; }
        public string CollectorName { get; set; }
        public Nullable<System.DateTime> DateIssued { get; set; }
        public string ClerkStaffNo { get; set; }
        public string ClerkName { get; set; }
        public string Status { get; set; }
        public string Reasons { get; set; }
        public string Expr7 { get; set; }
        public Nullable<System.DateTime> Expr8 { get; set; }
        public string Expr9 { get; set; }
        public long ChequeId { get; set; }
        public decimal IntAmount { get; set; }
        public decimal PaidBf { get; set; }
        public Nullable<System.DateTime> IntLoadeddate { get; set; }
        public Nullable<int> Expr10 { get; set; }
        public Nullable<double> Expr11 { get; set; }
        public string Expr12 { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<System.DateTime> Loadeddate { get; set; }
        public Nullable<double> Insuranceload { get; set; }
        public Nullable<double> IntLoad { get; set; }
        public string Expr13 { get; set; }
        public long Expr14 { get; set; }
        public string Expr15 { get; set; }
        public string Expr16 { get; set; }
        public string DeductionID { get; set; }
        public string STONo { get; set; }
        public decimal DedAmount { get; set; }
        public decimal Percentage { get; set; }
        public decimal DefAmount { get; set; }
        public string ProductID { get; set; }
        public string Source { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime LastTransDate { get; set; }
        public string Expr17 { get; set; }
        public System.DateTime Expr18 { get; set; }
        public decimal Expr19 { get; set; }
        public decimal Principal { get; set; }
        public string Expr20 { get; set; }
        public string ProductName { get; set; }
        public string GLAccNo { get; set; }
        public string ContraGLAccNo { get; set; }
        public string ProcessingFee { get; set; }
        public decimal Expr21 { get; set; }
        public decimal Expr22 { get; set; }
        public int BackOffice { get; set; }
        public int intervals { get; set; }
        public string Expr23 { get; set; }
        public System.DateTime Expr24 { get; set; }
    }
}
