//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDefauter
    {
        public string MemberNo { get; set; }
        public string LoanNo { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public decimal intrOwed { get; set; }
        public Nullable<int> RescheduledPeriod { get; set; }
        public Nullable<decimal> InitialAmount { get; set; }
        public Nullable<System.DateTime> DateIssued { get; set; }
        public Nullable<decimal> RepayRate { get; set; }
        public Nullable<int> ElapsedMonths { get; set; }
        public Nullable<int> RepayPeriod { get; set; }
        public Nullable<decimal> Expected { get; set; }
        public Nullable<decimal> PrincePaid { get; set; }
        public decimal paidInterest { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> Arrears { get; set; }
        public Nullable<int> period { get; set; }
        public decimal paidbf { get; set; }
    }
}
