//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwLoanGuarantorInformation
    {
        public string LoanCode { get; set; }
        public string LoanType { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string MemberNo { get; set; }
        public decimal Amount { get; set; }
        public string Surname { get; set; }
        public string OtherNames { get; set; }
        public decimal GuarantorAmount { get; set; }
        public string LoanOwner { get; set; }
        public string LoanNo { get; set; }
        public string OwenerMemberno { get; set; }
        public string StaffNo { get; set; }
        public string Unit { get; set; }
    }
}
