//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwLoanGuarantor
    {
        public string LoaneeMemberNo { get; set; }
        public string LoaneeNames { get; set; }
        public string GuarMemberNo { get; set; }
        public string GuarNames { get; set; }
        public decimal GuarBalance { get; set; }
        public decimal GuarAmount { get; set; }
        public string LoanNo { get; set; }
        public Nullable<decimal> Loanbalance { get; set; }
        public Nullable<int> transfered { get; set; }
    }
}
