//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwLoanDetail
    {
        public string LoanNo { get; set; }
        public string LoanCode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public string RepayMethod { get; set; }
        public Nullable<int> RepayPeriod { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string LoanAccNo { get; set; }
        public string InterestAccNo { get; set; }
        public string ContraAcc { get; set; }
    }
}
