//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwShareBalance
    {
        public string MemberNo { get; set; }
        public string Surname { get; set; }
        public string OtherNames { get; set; }
        public decimal totalshares { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public bool UsedToGuarantee { get; set; }
        public string SharesCode { get; set; }
        public string SharesType { get; set; }
    }
}
