//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WCHARGE
    {
        public long PKID { get; set; }
        public Nullable<decimal> OverAmount { get; set; }
        public Nullable<decimal> UptoAmount { get; set; }
        public Nullable<decimal> RateO { get; set; }
        public Nullable<long> Period { get; set; }
        public string Glaccount { get; set; }
        public Nullable<bool> userange { get; set; }
        public string CommID { get; set; }
        public short RangeNo { get; set; }
        public int Percentage { get; set; }
    }
}
