//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class xxxy
    {
        public string AccNo { get; set; }
        public string LoanNo { get; set; }
        public string Surname { get; set; }
        public string OtherNames { get; set; }
        public string MemberNo { get; set; }
        public string Purpose { get; set; }
        public string RepayMethod { get; set; }
        public Nullable<int> RepayPeriod { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public Nullable<System.DateTime> DateIssued { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public System.DateTime DOB { get; set; }
        public string IDNo { get; set; }
        public string MobileNo { get; set; }
        public string Sex { get; set; }
        public Nullable<decimal> RepayRate { get; set; }
    }
}
