//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zonesReport
    {
        public string MemberNo { get; set; }
        public string StaffNo { get; set; }
        public string Surname { get; set; }
        public string OtherNames { get; set; }
        public string zones { get; set; }
        public Nullable<decimal> ShareCapital { get; set; }
        public Nullable<decimal> Deposits { get; set; }
    }
}
